#**QUIZ**

In [72]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error
import sympy as sm

A = np.array([[2,1,3],
     [3,-2,1],
     [-1,0,1]])
B = np.array([[1,-2],
     [2,1],
     [4,-2]])
C = np.matmul(A, B)
C
D = A@B
D
E = np.dot(A,B)
print(C)
print(D)
print(E)

[[ 16  -9]
 [  3 -10]
 [  3   0]]
[[ 16  -9]
 [  3 -10]
 [  3   0]]
[[ 16  -9]
 [  3 -10]
 [  3   0]]


#**Exercise 1**

In [54]:
A = np.array([[0,1,1],
     [1,0,1],
     [1,1,0]])
B = np.array([[0,2,3],
     [0,5,0],
     [7,0,0]])

C = np.multiply(A,B)
print(C)
D = A*B
print(D)

[[0 2 3]
 [0 0 0]
 [7 0 0]]
[[0 2 3]
 [0 0 0]
 [7 0 0]]


In [6]:
D = A + B
D

array([[0, 3, 4],
       [1, 5, 1],
       [8, 1, 0]])

In [7]:
E = np.transpose(A)
E

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [9]:
F = A[1]
print(F)

[1 0 1]


In [12]:
a = A[:,-1]
b = B[-1]
c = a + b
print(a)
print(b)
print("a + b is ",c)

[1 1 0]
[7 0 0]
a + b is  [8 1 0]


#**Exercise 2**

Any norm above 2 aren't working with vertical and horizontal matrices

In [74]:
v = np.array([[2],
           [4],
           [1]])
u = np.array([[1],
            [3],
            [5]])

#v = np.array([2,4,1])
#v = np.array([[1,3,5]])
t = np.dot(u.reshape(1,3),v)
l = u.reshape(1,3)@v
print(t)
print(l)

[[19]]
[[19]]


In [75]:
from math import inf

vl1 = np.linalg.norm(v,1)
print("norm 1 is",vl1)
vl2 = np.linalg.norm(v,2)
print("norm 2 is",vl2)
vl3 = (v**3).sum(axis=1)**(1/3)
print("norm 3 is",vl3[0])
vl4 = (v**4).sum(axis=1)**(1/4)
print("norm 4 is",vl4[0])
vlmax = np.linalg.norm(v,inf)
print("norm max is",vlmax)

norm 1 is 7.0
norm 2 is 4.58257569495584
norm 3 is 2.0
norm 4 is 2.0
norm max is 4.0


In [76]:
ul1 = np.linalg.norm(u,1)
print("norm 1 is",ul1)
ul2 = np.linalg.norm(u,2)
print("norm 2 is",ul2)
ul3 = (u**3).sum(axis=1)**(1/3)
print("norm 3 is",ul3[0])
ul4 = (u**4).sum(axis=1)**(1/4)
print("norm 4 is",ul4[0])
ulmax = np.linalg.norm(u,inf)
print("norm max is",ulmax)

norm 1 is 9.0
norm 2 is 5.916079783099616
norm 3 is 1.0
norm 4 is 1.0
norm max is 5.0


In [80]:
k = v + u 
print(k)
kl1 = np.linalg.norm(k,1)
print("norm 1 is",kl1)
kl2 = np.linalg.norm(k,2)
print("norm 2 is",kl2)
kl3 = (k**3).sum(axis=0)**(1/3)
print("norm 3 is",kl3[0])
kl4 = (k**4).sum(axis=0)**(1/4)
print("norm 4 is",kl4[0])
klmax = np.linalg.norm(k,inf)
print("norm max is",klmax)

[[3]
 [7]
 [6]]
norm 1 is 16.0
norm 2 is 9.695359714832659
norm 3 is 8.368209391204644
norm 4 is 7.839989632806745
norm max is 7.0


#**Exercise 3**

In [88]:
import sympy as sm
from sympy import *

A = np.array([[2,3,1],[10,9,11]])
A = Matrix(A)

B = np.array([[2,-4,6],[-1,5,0]])
B = Matrix(B)

print(A.rref())
print("---------------------------------------------")
print(B.rref())

(Matrix([
[1, 0,  2],
[0, 1, -1]]), (0, 1))
---------------------------------------------
(Matrix([
[1, 0, 5],
[0, 1, 1]]), (0, 1))


In [89]:
C = np.array([[1, 1, 0],
               [1, 2, 1],
               [0, 1, 2]])

C = Matrix(C)
C.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [90]:
D = Matrix(([[1, 1, 1, 7],
               [1, 1, -1, 5],
               [1, -1, 1, 3]]))

E = Matrix([[1, 1, 1, 7],
               [1, 1, -1, 5],
               [-1, -1, 1, 3]])
D.rref()

(Matrix([
 [1, 0, 0, 4],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]), (0, 1, 2))

In [92]:
E.rref()

(Matrix([
 [1, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]), (0, 2, 3))