#**Homework**

In [ ]:
import numpy as np
import sympy as sm

##**1**

In [ ]:
w = np.array([[-5],[11],[8]])
V = np.array([[1,0,2],
              [-2,5,0],
              [2,5,8]])
aug = np.concatenate((V,w),axis=1)
sm.Matrix(aug).rref()

(Matrix([
 [1, 0,   2, 0],
 [0, 1, 4/5, 0],
 [0, 0,   0, 1]]), (0, 1, 3))

##**2**

In [ ]:
set_vectors = np.array([[1, 1, 0],
                        [0, 2, 1],
                        [1, 2, 2],
                        [2, 1, 1]])
sm.Matrix(set_vectors).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 0]]), (0, 1, 2))

**this set is dependant as they have infinte solutions for a and b and c**

##**3**

**Ve = b_basis * Vb , Vb = inv_b_basis * Ve**

In [61]:
b = np.array([[3, 4],
              [4, -3]])
ve = Ve = np.array([[10],
              [-5]])
b_inverse = np.linalg.inv(b)
vb = b_inverse@ve
vb

array([[0.4],
       [2.2]])

In [ ]:
b_inverse = np.linalg.inv(b)
ve = b_inverse@vb
ve

array([[10.],
       [-5.]])

##**4**

In [ ]:
T_A = np.array([[0,2,-1],
              [3,1,1],
              [0,-1,-2]])

T_A@ np.eye(3)

array([[ 0.,  2., -1.],
       [ 3.,  1.,  1.],
       [ 0., -1., -2.]])

In [ ]:
B = np.array([[1,-1,1],
                [0,1,2],
                [0,0,-1]])
T_A@B

array([[ 0,  2,  5],
       [ 3, -2,  4],
       [ 0, -1,  0]])

##**5**

In [ ]:
np.linalg.inv([[1,1],[1,-1]])

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [ ]:
np.linalg.inv([[1,2],[3,5]])

array([[-5.,  2.],
       [ 3., -1.]])

In [ ]:
np.linalg.inv([[1,0,1],[0,1,1],[1,1,1]])

array([[ 0., -1.,  1.],
       [-1.,  0.,  1.],
       [ 1.,  1., -1.]])

##**6**

In [ ]:
b_basis = np.array([[1, -1, 1],
                    [1, 1, 2],
                    [1, 0, 1]])
sm.Matrix(b_basis).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [ ]:
v = np.array([[3],[2],[4]])
T_reflection = np.array([[1,0,0],
                        [0,1,0],
                        [0,0,-1]])
inv_b_basis = np.linalg.inv(b_basis)
b_basis@T_reflection@inv_b_basis@v

array([[ 9.],
       [14.],
       [10.]])

In [ ]:
np.linalg.det(b_basis)
#the determinant != zero, so the basis are not orthonormal

-1.0

In [ ]:
def projection(x,y):

  return ((x@y) / np.linalg.norm(y,2)**2) * y

In [ ]:
u1 = b_basis[:,0]
u2 = b_basis[:,1] - projection(b_basis[:, 1], u1)
u3 = b_basis[:, 2] - projection(b_basis[:, 2], u1) - projection(b_basis[:, 2], u2)
print(u1,u2,u3)
e1 = u1/np.linalg.norm(u1,2)
e2 = u2/np.linalg.norm(u2,2)
e3 = u3/np.linalg.norm(u3,2)
print(e1,e2,e3)

[1 1 1] [-1.  1.  0.] [ 0.16666667  0.16666667 -0.33333333]
[0.57735027 0.57735027 0.57735027] [-0.70710678  0.70710678  0.        ] [ 0.40824829  0.40824829 -0.81649658]


##**7**

In [ ]:
basis = np.array([[0,1,1,1],
                   [2,-1,2,0],
                   [1,0,0,0],
                   [0,0,-1,1]])
sm.Matrix(basis).rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]), (0, 1, 2, 3))

In [ ]:
u1 = basis[:,0]
u2 = basis[:,1] - projection(basis[:, 1], u1) 
u3 = basis[:, 2] - projection(basis[:, 2], u1) - projection(basis[:, 2], u2)                                                             
u4 = basis[:, 3] - projection(basis[:, 3], u1) - projection(basis[:, 3], u2) - projection(basis[:, 3], u3)
print(u1,u2,u3,u4)
e1 = u1 / np.linalg.norm(u1)
e2 = u2 / np.linalg.norm(u2)
e3 = u3 / np.linalg.norm(u3)
e4 = u4 / np.linalg.norm(u4)
print(e1,e2,e3,e4)

[0 2 1 0] [ 1.  -0.2  0.4  0. ] [ 0.5  0.5 -1.  -1. ] [ 0.26666667  0.26666667 -0.53333333  0.8       ]
[0.         0.89442719 0.4472136  0.        ] [ 0.91287093 -0.18257419  0.36514837  0.        ] [ 0.31622777  0.31622777 -0.63245553 -0.63245553] [ 0.25819889  0.25819889 -0.51639778  0.77459667]


#**QUIZ**

##**1**

In [ ]:
v = np.array([[4], [7], [-1]])
S = np.eye(3)
aug = np.concatenate((S,v), axis = 1)
sm.Matrix(aug).rref()

(Matrix([
 [  1,   0, 0,  4.0],
 [0.0,   1, 0,  7.0],
 [0.0, 0.0, 1, -1.0]]), (0, 1, 2))

**v is in the span on S as they are independant orthogonal vectors**

##**2**

**a * v1 + b * v2 + c * v3 = 0**

In [ ]:
v1 = [[4],[5]]
v2 = [[1],[2]]
v3 = [[0],[1]]
r = [[0],[0]]
M = np.concatenate((v1,v2,v3,r),axis=1)
sm.Matrix(M).rref()

(Matrix([
 [1, 0, -1/3, 0],
 [0, 1,  4/3, 0]]), (0, 1))

**The third vector is a linear combination of the first and second vector**
**a = -1/3**
**b = 4/3**

##**3**

In [ ]:
M = [[1,0,0],
     [0,1,2],
     [0,0,1]]
sm.Matrix(M).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

**yes because they are linearly independant**

##**4**

In [ ]:
M = np.eye(4)

sm.Matrix(M).rref()

(Matrix([
 [  1,   0,   0, 0],
 [0.0,   1,   0, 0],
 [0.0, 0.0,   1, 0],
 [0.0, 0.0, 0.0, 1]]), (0, 1, 2, 3))

**yes because they are linearly independant**

##**5**

**Ve = b_basis * Vb , Vb = inv_b_basis * Ve**

In [60]:
Vb = np.array([[1], 
               [3]])
b_basis = np.array(np.array([[4.5, -0.5],
                             [-2.5, 0.5]]))
#b_inverse = np.linalg.inv(b_basis)
Ve = b_basis @Vb
Ve

array([[ 3.],
       [-1.]])

##**6**

**Reflection**

In [ ]:
Tr = np.array([[1,0],
              [0,-1]])
Tr

array([[ 1,  0],
       [ 0, -1]])

**Shear**

In [ ]:
Ts = np.array([[1, 1],
              [0, 1]])
Ts

array([[1, 1],
       [0, 1]])

##**7**

In [ ]:
np.linalg.det(np.array([[2,-1],
                        [3, -5]]))

-6.999999999999999

In [ ]:
np.linalg.det(np.array([[1,3, -2],
                        [0, 1, 4],
                        [0, 1, 1]]))

-3.0000000000000004

In [ ]:
np.linalg.det(np.array([[12,3, 1],
                        [2, 0, 2],
                        [18, 0, 1]]))

102.00000000000004

In [ ]:
np.linalg.det(np.array([[1, 2, 3],
          [3, 6, 9]]))


**has no determinant, as the matrix is not square**

##**8**

In [ ]:
np.linalg.inv(np.array([[2,-1],
                        [3, -5]]))

array([[ 0.71428571, -0.14285714],
       [ 0.42857143, -0.28571429]])

In [ ]:
np.linalg.inv(np.array([[1,3, -2],
                        [0, 1, 4],
                        [0, 1, 1]]))

array([[ 1.        ,  1.66666667, -4.66666667],
       [ 0.        , -0.33333333,  1.33333333],
       [-0.        ,  0.33333333, -0.33333333]])

In [ ]:
np.linalg.inv(np.array([[12,3, 1],
                        [2, 0, 2],
                        [18, 0, 1]]))

array([[ 0.        , -0.02941176,  0.05882353],
       [ 0.33333333, -0.05882353, -0.21568627],
       [ 0.        ,  0.52941176, -0.05882353]])

In [ ]:
np.linalg.inv(np.array([[1, 2, 3],
          [3, 6, 9]]))

**The matrix has no inverse,becuase it has no determinant**