In [1]:
import numpy as np

### Practice some NumPy commands:
- Create 3 * 3 array.
- Check its shape.
- Select first row.
- Select 2nd column.
- Select the 2nd element in the third column.
- Create 2*2 from the first two elements of the first 2 rows and columns.
- Create single row vector.
- Create single column vector.

In [6]:
X = np.arange(1,10).reshape(3,3)
X
X.shape

(3, 3)

In [12]:
X[0,:]

array([1, 2, 3])

In [13]:
X[:,1]

array([2, 5, 8])

In [14]:
X[1][2]

6

In [17]:
X[:2,:2].reshape(2,2)

array([[1, 2],
       [4, 5]])

In [20]:
Y = np.array([1,2,3]).reshape(1,3)
Y

array([[1, 2, 3]])

In [19]:
Z = np.array([4,5,6]).reshape(3,1)
Z

array([[4],
       [5],
       [6]])

## Represent in paper and as numpy arrays Ax=b


In [22]:
A = np.array([[3,-1]
              ,[1,0]])
A_aug = np.array([[3,-1,2]
              ,[1,0,4]])
A_result = np.array([[2],[4]])

B = np.array([[3,-2]
              ,[2,-2]])
B_aug = np.array([[3,-2,7]
              ,[2,-2,2]])
B_result = np.array([[7],[2]])


C = np.array([[3,-2,1]
              ,[1,1,1],
              [3,-2,-1]])
C_aug = np.array([[3,-2,1,7]
              ,[1,1,1,2],
              [3,-2,-1,3]])
C_result = np.array([[7],[2],[3]])


### Using numpy arrays
- Multiply matrix <b>A</b> and vector <b>x</b> and make sure the result is <b>b</b> from the above exercise.

In [29]:
x1= np.array([[ 4.]
,[10.]])
x2= np.array([[5.]
 ,[4.]])
x3= np.array([[ 1.]
 ,[-1.]
 ,[ 2.]])

print(A@x1 == A_result)
print(B@x2 == B_result)
print(C@x3 == C_result)

[[ True]
 [ True]]
[[ True]
 [ True]]
[[ True]
 [ True]
 [ True]]


## Calculate in paper then confirm your results using numpy linalg.norm().


In [36]:
from numpy import linalg
from math import inf

x = np.array([1,2,3])
print(linalg.norm(x,1))
print(linalg.norm(x,2))
print(linalg.norm(x,inf))
print("---------------------")
y = np.array([3,3,1,3])
print(linalg.norm(y,1))
print(linalg.norm(y,2))
print(linalg.norm(y,inf))
print("---------------------")
z = np.array([2,3,4])
print(linalg.norm(z,3))

6.0
3.7416573867739413
3.0
---------------------
10.0
5.291502622129181
3.0
---------------------
4.626065009182741


## Calculate in paper then confirm your results using numpy.
### Calculate L1, L2, L3, and Lmax for the following vectors:
### [5,6], [4,3,2], [4,3,2,8,9].

In [35]:
x = np.array([5,6])
print(linalg.norm(x,1))
print(linalg.norm(x,2))
print(linalg.norm(x,3))
print(linalg.norm(x,inf))
print("---------------------")
y = np.array([4,3,2])
print(linalg.norm(y,1))
print(linalg.norm(y,2))
print(linalg.norm(y,3))
print(linalg.norm(y,inf))
print("---------------------")
z = np.array([4,3,2,8,9])
print(linalg.norm(z,1))
print(linalg.norm(z,2))
print(linalg.norm(z,3))
print(linalg.norm(z,inf))

11.0
7.810249675906654
6.986368027818105
6.0
---------------------
9.0
5.385164807134504
4.626065009182741
4.0
---------------------
26.0
13.19090595827292
11.02473771449733
9.0


## Calculate in paper then confirm your results using numpy.


In [52]:
x = np.array([2,-1,5,0])
y = np.array([[4]
              ,[-3],
              [1],
              [-1]])
x@y

array([16])

In [53]:
x2 = np.array([3,2,-1,4])
y2 = np.array([[1]
              ,[-1],
              [1],
              [0]])
x2@y2

array([0])

## Calculate in paper then confirm your results using numpy.
### Create two vectors in 2, 3, and 4 dimensions.
### Perform vector addition, subtraction, and dot product of these vectors.

In [44]:
A_2D = np.arange(9).reshape(3,3)
B_2D = np.arange(9,0,-1).reshape(3,3)

A_3D = np.arange(18).reshape(2,3,3)
B_3D = np.arange(18,0,-1).reshape(2,3,3)

A_4D = np.arange(36).reshape(2,2,3,3)
B_4D = np.arange(36,0,-1).reshape(2,2,3,3)

In [49]:
C_2D = A_2D + B_2D
print(C_2D)
print("---------------------")
D_2D = A_2D - B_2D
print(D_2D)
print("---------------------")
E_2D = A_2D @ B_2D
print(E_2D)

[[9 9 9]
 [9 9 9]
 [9 9 9]]
---------------------
[[-9 -7 -5]
 [-3 -1  1]
 [ 3  5  7]]
---------------------
[[ 12   9   6]
 [ 66  54  42]
 [120  99  78]]


In [50]:
C_3D = A_3D + B_3D
print(C_3D)
print("---------------------")
D_3D = A_3D - B_3D
print(D_3D)
print("---------------------")
E_3D = A_3D @ B_3D
print(E_3D)

[[[18 18 18]
  [18 18 18]
  [18 18 18]]

 [[18 18 18]
  [18 18 18]
  [18 18 18]]]
---------------------
[[[-18 -16 -14]
  [-12 -10  -8]
  [ -6  -4  -2]]

 [[  0   2   4]
  [  6   8  10]
  [ 12  14  16]]]
---------------------
[[[ 39  36  33]
  [174 162 150]
  [309 288 267]]

 [[174 144 114]
  [228 189 150]
  [282 234 186]]]


In [51]:
C_4D = A_4D + B_4D
print(C_4D)
print("---------------------")
D_4D = A_4D - B_4D
print(D_4D)
print("---------------------")
E_4D = A_4D @ B_4D
print(E_4D)

[[[[36 36 36]
   [36 36 36]
   [36 36 36]]

  [[36 36 36]
   [36 36 36]
   [36 36 36]]]


 [[[36 36 36]
   [36 36 36]
   [36 36 36]]

  [[36 36 36]
   [36 36 36]
   [36 36 36]]]]
---------------------
[[[[-36 -34 -32]
   [-30 -28 -26]
   [-24 -22 -20]]

  [[-18 -16 -14]
   [-12 -10  -8]
   [ -6  -4  -2]]]


 [[[  0   2   4]
   [  6   8  10]
   [ 12  14  16]]

  [[ 18  20  22]
   [ 24  26  28]
   [ 30  32  34]]]]
---------------------
[[[[  93   90   87]
   [ 390  378  366]
   [ 687  666  645]]

  [[ 714  684  654]
   [ 930  891  852]
   [1146 1098 1050]]]


 [[[ 849  792  735]
   [ 984  918  852]
   [1119 1044  969]]

  [[ 498  414  330]
   [ 552  459  366]
   [ 606  504  402]]]]


## Calculate in paper then confirm your results using numpy.


In [58]:
A = np.array([[3,1,0],
     [2,1,2]])
B = np.array([[1,3],
     [2,5],
     [-1,3]])
C = np.matmul(A,B)
C.transpose()

array([[ 5,  2],
       [14, 17]])

In [60]:
A = np.array([[1,0,3],
     [4,5,-1]
     ,[0,0,2]])
B = np.array([[1],
     [2],
     [5]])
C = np.matmul(A,B)
C.transpose()

array([[16,  9, 10]])

## Different Types of Matrices
#### Create 3 by 3 and 4 by 4 identity matrices 

In [62]:
from numpy import identity
a = identity(3)
print(a)
b = identity(4)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Create a diagonal matrix contains [2,4,5,11] numbers in it's diagonal.

In [65]:
from numpy import diag
a = diag([2,4,5,11],k=0)
a

array([[ 2,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  5,  0],
       [ 0,  0,  0, 11]])

#### Create a 5 by 5 scalar matrix of number 7

In [66]:
b = np.ones((5,5))*7
b

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

#### Using SymPy get the rref of the following matrices

In [69]:
from numpy.matrixlib.defmatrix import matrix
import sympy as sm 

A = np.array([[1,0,1,3],
              [2,3,4,7],
              [-1,-3,-3,-4]])
M = sm.Matrix(A)
M

Matrix([
[ 1,  0,  1,  3],
[ 2,  3,  4,  7],
[-1, -3, -3, -4]])

In [70]:
M.rref()

(Matrix([
 [1, 0,   1,   3],
 [0, 1, 2/3, 1/3],
 [0, 0,   0,   0]]), (0, 1))

In [71]:
B = np.array([[1,1,1],
              [1,2,2],
              [1,2,3]])
M = sm.Matrix(B)
M

Matrix([
[1, 1, 1],
[1, 2, 2],
[1, 2, 3]])

In [72]:
M.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

In [73]:
C = np.array([[1,2,3],
              [2,-1,1],
              [3,0,-1]])
M = sm.Matrix(C)
M

Matrix([
[1,  2,  3],
[2, -1,  1],
[3,  0, -1]])

In [74]:
M.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

#### Find the solution of the following system of linear equation using SymPy Matrix rref()

In [76]:
S = sm.Matrix(np.array([[1,1,1,6],
              [1,2,2,9],
              [1,2,3,10]]))
S.rref()

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 2],
 [0, 0, 1, 1]]), (0, 1, 2))

In [77]:
S = sm.Matrix(np.array([[1,2,3,9],
              [2,-1,1,8],
              [3,0,-1,3]]))
S.rref()

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]), (0, 1, 2))

#### Find the solution of the following system of linear equation 
- By hand (Paper and pen)
- Confirm your answer using SymPy Matrix rref()

In [79]:
S = np.array([[1,2,3,6],
              [2,5,2,4],
              [6,-3,1,2]])
S1 = sm.Matrix(S)
S1.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 2]]), (0, 1, 2))

In [80]:
S = np.array([[2,4,-2,2],
              [4,9,-3,8],
              [-2,-3,7,10]])
S1 = sm.Matrix(S)
S1.rref()

(Matrix([
 [1, 0, 0, -1],
 [0, 1, 0,  2],
 [0, 0, 1,  2]]), (0, 1, 2))

In [81]:
S = np.array([[1,-2,1],
              [3,-6,11]])
S1 = sm.Matrix(S)
S1.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]), (0, 2))

In [82]:
S = np.array([[1,-2,1],
              [3,-6,3]])
S1 = sm.Matrix(S)
S1.rref()

(Matrix([
 [1, -2, 1],
 [0,  0, 0]]), (0,))