## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [ ]:
import numpy as np 
import sympy as sm

b = 3*np.array([[1],[2],[3]])
print(b)

[[3]
 [6]
 [9]]


In [ ]:
x = -1*np.array([[1],[2],[3]]) + np.array([[3],[5],[1]]) -0.5*np.array([[0],[0],[8]])
print(x)

[[ 2.]
 [ 3.]
 [-6.]]


## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of 
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [ ]:
v = sm.Matrix(np.array([[3,-5,1,19],[-1,0,7,10],[2,1,-4,-1]]))
v.rref()

(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]), (0, 1, 2))

In [ ]:
v.rref()[0][:,-1]

Matrix([
[ 4],
[-1],
[ 2]])

## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it. 
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [ ]:
M = sm.Matrix([[2,1,1,0],
            [0,1,7,0],
            [-3,1,2,0]])

In [ ]:
M.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0]]), (0, 1, 2))

In [ ]:
N = np.array([[2,1,1],
            [0,1,7],
            [-3,1,2]])
np.linalg.det(N)

-28.00000000000001

In [ ]:
M = sm.Matrix([[1,4,-10,0],
            [2,1,1,0],
            [-1,3,-11,0]])

In [ ]:
M.rref()

(Matrix([
 [1, 0,  2, 0],
 [0, 1, -3, 0],
 [0, 0,  0, 0]]), (0, 1))

In [ ]:
N = np.array([[1,4,-10],
            [2,1,1],
            [-1,3,-11]])
np.linalg.det(N)

0.0

## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y. 
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [ ]:
T = np.array([[1,2],[3,7]])
v1 = np.array([[1],[0]])
v2 = np.array([[0],[1]])

In [ ]:
print(T@v1)
print(T@v2)

[[1]
 [3]]
[[2]
 [7]]


In [ ]:
np.linalg.inv(T)@v1

array([[ 7.],
       [-3.]])

### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Represent the transformation graphically <b>(on paper)</b>.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

In [ ]:
#v1 = np.array([[1],[1]])
#v2 = np.array([[2],[1]])
#T = np.linalg.inv(v1).transpose()@np.array(v2)

T = np.array([[1,1],[0,1]])

solution = np.linalg.inv(T)@np.array([[3],[4]])
solution

array([[-1.],
       [ 4.]])

x:
[[-1.]
 [ 4.]]


## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [ ]:
m1 = np.array([[3,8],[4,6]])
m2 = np.array([[4,6],[3,8]])
m3 = np.array([[6,1,1],[4,-2,5],[2,8,7]])
m4 = np.array([[3,2,0,1],[4,0,1,2],[3,0,2,1],[9,2,3,1]])

print(np.linalg.det(m1))
print(np.linalg.det(m2))
print(np.linalg.det(m3))
print(np.linalg.det(m4))

-14.000000000000004
14.000000000000004
-306.0
24.000000000000004


1.  -14.000000000000004
2.  14.000000000000004
3.  -306.0
4.  24.000000000000004


## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [ ]:
X = np.array([[1,2,4,4],[3,4,8,0]])
M = sm.Matrix(X)
print(M.rref())
print("X rank: ",np.linalg.matrix_rank(X))

(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))
X rank:  2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


In [ ]:
X = np.array([[1,2,3],[2,3,5],[3,4,7],[4,5,9]])
M = sm.Matrix(X)
print(M.rref())
print("X rank: ",np.linalg.matrix_rank(X))

(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))
X rank:  2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [ ]:
m1 = np.array([[3,8],[4,6]])
m2 = np.array([[4,6],[3,8]])
m3 = np.array([[6,1,1],[4,-2,5],[2,8,7]])
m4 = np.array([[3,2,0,1],[4,0,1,2],[3,0,2,1],[9,2,3,1]])

print(np.linalg.inv(m1))
print(np.linalg.inv(m2))
print(np.linalg.inv(m3))
print(np.linalg.inv(m4))

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]
[[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


**bold text**## Changing Basis (Orthogonal Coordinates)
### Perform the following (Once by dot product and another by matix). 
### First confirm b1 and b2 are orthogonal basis.


In [5]:
v = np.array([[5],[-1]])
b1 = np.array([[1],[1]])
b2 = np.array([[1],[-1]])

a = v.transpose()@b1/np.linalg.norm(b1,2)**2
b = v.transpose()@b2/np.linalg.norm(b2,2)**2
print(a,b)

[[2.]] [[3.]]


In [10]:
import numpy as np
import sympy as sm 
b = np.concatenate((b1,b2),axis = 1)
np.linalg.inv(b) @ v

array([[2.],
       [3.]])

Using dot product
vb:
[[2.]
 [3.]]


Using transformation matrix
vb:
[[2.]
 [3.]]


In [12]:
v = np.array([[10],[-5]])
b1 = np.array([[3],[4]])
b2 = np.array([[4],[-3]])

a = v.transpose()@b1/np.linalg.norm(b1,2)**2
b = v.transpose()@b2/np.linalg.norm(b2,2)**2
print(a,b)

[[0.4]] [[2.2]]


In [13]:
b = np.concatenate((b1,b2),axis = 1)
np.linalg.inv(b) @ v

array([[0.4],
       [2.2]])

## Changing Basis (Non-Orthogonal Coordinates)
### Perform the following. 
### First confirm b1 and b2 are non-orthogonal basis.


In [15]:
v = np.array([[5], [2]])

b1 = np.array([[3], [1]])

b2 = np.array([[1], [1]])

B = np.concatenate((b1,b2), axis=1)
np.linalg.inv(B) @ v

array([[1.5],
       [0.5]])

vb:
[[1.5]
 [0.5]]


## Transformation in Non-Orthonormal Space


In [18]:
b1 = np.array([[3], [1]])
b2 = np.array([[1], [1]])

B = np.concatenate((b1,b2),axis=1)

ref_T_e = np.array([[1, 0],
                  [0, -1]])

rot_T_e = np.array([[0, 1],
                  [-1, 0]])

v = np.array([[1.5], [0.5]])

In [26]:
TB1 = np.around(np.linalg.inv(B)@ ref_T_e @ B )
TB1

array([[ 2.,  1.],
       [-3., -2.]])

In [22]:
TB2 = np.around(np.linalg.inv(B) @ rot_T_e @ B)
TB2

array([[ 2.,  1.],
       [-5., -2.]])

In [23]:
TB1@v

array([ 3.5, -5.5])

In [24]:
TB2@v

array([ 3.5, -8.5])

TB1 =
 [[ 2.  1.]
 [-3. -2.]]

TB2 =
 [[ 2.  1.]
 [-5. -2.]]

vb_TB1 =
 [[ 3.5]
 [-5.5]]

vb_TB2 =
 [[ 3.5]
 [-8.5]]


## Gram–Schmidt Process (Orthogonalization)

#### Confirm your answer using numpy.linalg.qr() function
#### Make sure all vectors given above are basis in R3 space.
#### Confirm that the orthogonal matrix has orthonormal vectors.
#### Confirm that the transpose of the orthogonal matrix is it's inverse.
#### Reflect the vector r = (1,3,4) arround the xy plane.
#### Round all results to 3 decimal points.

In [27]:
v1 = np.array([[1], [2], [0]])

v2 = np.array([[8], [1], [-6]])

v3 = np.array([[0], [0], [1]])

v = np.concatenate((v1,v2,v3),axis=1)


array([[ 1,  8,  0],
       [ 2,  1,  0],
       [ 0, -6,  1]])

In [29]:
#### Make sure all vectors given above are basis in R3 space.
print(np.linalg.det(v))
print(sm.Matrix(v).rref())

-15.0
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


det(V): -15.0
Mrref:
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [34]:
### Orthogonalization

u1 = v1
print(u1)
e1 = u1/np.linalg.norm(u1)
print(e1)

[[1]
 [2]
 [0]]
[[0.4472136 ]
 [0.89442719]
 [0.        ]]


In [33]:
u2 = v2 - (v2.T@u1)/(u1.T@u1) * u1
print(u2)
e2 = u2/np.linalg.norm(u2)
print(e2)

[[ 6.]
 [-3.]
 [-6.]]
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]


In [35]:
u3 = v3 - (v3.T@u1)/(u1.T@u1) * u1 - (v3.T@u2)/(u2.T@u2) * u2
print(u3)
e3 = u3/np.linalg.norm(u3)
print(e3)

[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


u1:
[[1]
 [2]
 [0]]

u2:
[[ 6.]
 [-3.]
 [-6.]]

u3:
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]

e1:
[[0.4472136 ]
 [0.89442719]
 [0.        ]]

e2:
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]

e3:
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


In [37]:
B = np.concatenate((e1, e2, e3), axis=1)
print(B)
print(B.T)
print(np.linalg.inv(B))

[[ 0.4472136   0.66666667  0.59628479]
 [ 0.89442719 -0.33333333 -0.2981424 ]
 [ 0.         -0.66666667  0.74535599]]
[[ 0.4472136   0.89442719  0.        ]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.59628479 -0.2981424   0.74535599]]
[[ 0.4472136   0.89442719  0.        ]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.59628479 -0.2981424   0.74535599]]


In [39]:
Q, R = np.linalg.qr(v)
Q

array([[-0.4472136 ,  0.66666667,  0.59628479],
       [-0.89442719, -0.33333333, -0.2981424 ],
       [-0.        , -0.66666667,  0.74535599]])

Using QR:
[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


In [40]:
print(Q.T)
print(np.linalg.inv(Q))

[[-0.4472136  -0.89442719 -0.        ]
 [ 0.66666667 -0.33333333 -0.66666667]
 [ 0.59628479 -0.2981424   0.74535599]]
[[-4.47213595e-01 -8.94427191e-01 -9.30950307e-17]
 [ 6.66666667e-01 -3.33333333e-01 -6.66666667e-01]
 [ 5.96284794e-01 -2.98142397e-01  7.45355992e-01]]


In [41]:
ref_T = np.array([[1, 0, 0],
                  [0, 1, 0],
                  [0, 0, -1]])

r = np.array([[1], [3], [4]])

ref_T_non = B @ ref_T @ np.linalg.inv(B)
ref_T_non

array([[ 0.28888889,  0.35555556, -0.88888889],
       [ 0.35555556,  0.82222222,  0.44444444],
       [-0.88888889,  0.44444444, -0.11111111]])

In [44]:
np.around(ref_T_non @ r, 3)

array([[-2.2],
       [ 4.6],
       [ 0. ]])

Transformation matrix in the non-orthonormal basis:
[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]

Transformed vector:
[[-2.2]
 [ 4.6]
 [ 0. ]]
